# Generated by Django 4.1.6 on 2023-02-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fooddata',
            fields=[
                ('food_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('food_name', models.TextField()),
                ('kcal', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('water', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('carbo', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ile', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('leu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('lys', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('met', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cys', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('phe', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tyr', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('thr', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('trp', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('val', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('his', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('arg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('asp', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('glu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('gly', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pro', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ser', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('hyp', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'fooddata',
                'managed': False,
            },
        ),
    ]
