# Generated by Django 4.1.6 on 2023-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('food_name', models.TextField()),
                ('kcal', models.FloatField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carbo', models.FloatField(blank=True, null=True)),
                ('ile', models.FloatField(blank=True, null=True)),
                ('leu', models.FloatField(blank=True, null=True)),
                ('lys', models.FloatField(blank=True, null=True)),
                ('met', models.FloatField(blank=True, null=True)),
                ('cys', models.FloatField(blank=True, null=True)),
                ('phe', models.FloatField(blank=True, null=True)),
                ('tyr', models.FloatField(blank=True, null=True)),
                ('thr', models.FloatField(blank=True, null=True)),
                ('trp', models.FloatField(blank=True, null=True)),
                ('val', models.FloatField(blank=True, null=True)),
                ('his', models.FloatField(blank=True, null=True)),
                ('arg', models.FloatField(blank=True, null=True)),
                ('asp', models.FloatField(blank=True, null=True)),
                ('glu', models.FloatField(blank=True, null=True)),
                ('gly', models.FloatField(blank=True, null=True)),
                ('pro', models.FloatField(blank=True, null=True)),
                ('ser', models.FloatField(blank=True, null=True)),
                ('hyp', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fooddata',
            fields=[
                ('food_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('food_name', models.TextField()),
                ('kcal', models.FloatField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carbo', models.FloatField(blank=True, null=True)),
                ('ile', models.FloatField(blank=True, null=True)),
                ('leu', models.FloatField(blank=True, null=True)),
                ('lys', models.FloatField(blank=True, null=True)),
                ('met', models.FloatField(blank=True, null=True)),
                ('cys', models.FloatField(blank=True, null=True)),
                ('phe', models.FloatField(blank=True, null=True)),
                ('tyr', models.FloatField(blank=True, null=True)),
                ('thr', models.FloatField(blank=True, null=True)),
                ('trp', models.FloatField(blank=True, null=True)),
                ('val', models.FloatField(blank=True, null=True)),
                ('his', models.FloatField(blank=True, null=True)),
                ('arg', models.FloatField(blank=True, null=True)),
                ('ala', models.FloatField(blank=True, null=True)),
                ('asp', models.FloatField(blank=True, null=True)),
                ('glu', models.FloatField(blank=True, null=True)),
                ('gly', models.FloatField(blank=True, null=True)),
                ('pro', models.FloatField(blank=True, null=True)),
                ('ser', models.FloatField(blank=True, null=True)),
                ('hyp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fooddata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('food_name', models.TextField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'food_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('remember_token', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
